--
- hosts: [all_hosts]
  become: true
  tasks:
    - name: install php
      yum: name=php state=installed disable_gpg_check=yes
      register: php_install

    - name: checking php
      command: php -v
      when: php_install is success



Step to run a playbook 

ansible-playbook --syntax-check playbook_name.yml --->  check the syntax
ansible-playbook playbook_name.yaml --check --- > dry run 
ansible-playbook sampleplaybook.yaml  --- >executing the code
